name: Mark stale issues and pull requests

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  stale:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/stale@v6.0.0
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue is being marked as stale due to a long period of inactivity'
        stale-pr-message: 'This PR is being marked as stale due to a long period of inactivity'
        stale-issue-label: 'kind/stale'
        stale-pr-label: 'kind/stale'
        exempt-issue-label: 'kind/stale'
        exempt-pr-label: 'kind/stale'
